[package]
name = "cli-calculator-program"
version = "0.1.0"
edition = "2021"
authors = ["Kaique Pacheco kaique12br@gmail.com"]
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
